apiVersion: batch/v1
kind: Job
metadata:
  name: configmap-checksum-updater
  namespace: aws-ec2-instance-checker
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: updater
        image: alpine:3.13
        command:
        - /bin/sh
        - -c
        args:
        - |
          apk --no-cache add openssl
          CHECKSUM=$(openssl dgst -sha256 -hex /policies/policy.rego | cut -d' ' -f2)
          kubectl patch deployment opa -n aws-ec2-instance-checker --patch "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"configmap.revision\": \"$CHECKSUM\"}}}}}"
        volumeMounts:
        - name: policy
          mountPath: /policies
      volumes:
      - name: policy
        configMap:
          name: opa-policy
