apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-ec2-instance-checker.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: {{ include "aws-ec2-instance-checker.name" . }}