apiVersion: v1
data:
  check_aws-ec2-instance-checkerv1.rego: |
    package ec2

    default result = false

    # Rule to check if the instance has a public IP address
    result {
        input.public_ip != "None"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opa-policy