apiVersion: v1
data:
  check_imdsv1.rego: |
    package ec2

    default match = false

    # Check if an instance's associated role has the AmazonSSMManagedInstanceCore managed policy tewst
    match {
        some i
        input.Reservations[_].Instances[_].IamInstanceProfile.Arn == "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opa-policy