apiVersion: v1
data:
  check_imdsv1.rego: |
    package ec2

    default public_exposed = false

    # Rule to check if the instance has a public IP address
    public_exposed {
        input.public_ip != "None"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opa-policy