apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa
spec:
  replicas: {{ .Values.opa.replicaCount }}
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
      annotations:
        configmap.revision: {{ (include "opa-policy" .) | sha256sum }}
    spec:
      containers:
        - name: opa
          image: "{{ .Values.opa.image.repository }}:{{ .Values.opa.image.tag }}"
          imagePullPolicy: {{ .Values.opa.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.opa.containerPort }}
          args:
            - "run"
            - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
            - "--server"
            - "/policies"
          volumeMounts:
            - readOnly: true
              mountPath: /policies
              name: check-imdsv1-policy
      volumes:
        - name: check-imdsv1-policy
          configMap:
            name: opa-policy
