apiVersion: v1
data:
  check_imdsv1.rego: |
    package ec2

    default match = false

    # Check if an instance's associated role has the AmazonSSMManagedInstanceCore managed policy
    match {
        some i
        input.Role.Policies[i] == "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
    }


kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opa-policy
  annotations:
    checksum/data: {{ .Files.Get "helm/aws-ec2-instance-checker/templates/opa-configmap.yaml" | sha256sum }}
